### ISSUE TITLE
Re-implement graphical display of database search results

### ISSUE THREAD

**Issue by staszekdh** [labstructbioinf/pLM-BLAST#31]
Rewrite [https://github.com/labstructbioinf/pLM-BLAST/blob/main/scripts/plot.py](url) and integrate with the current version.

**Comment by DaRinker** [comment]
The plot.py script seems to be broken for me:

`$ python $PLMBLAST_PATH/scripts/plot.py output.csv query.fasta plot.png -mode score -ecod
Traceback (most recent call last):
  File "/home/bin/pLM-BLAST/scripts/plot.py", line 82, in <module>
    query_seq = query_df.loc[qid].sequence
  File "/home/resources/conda_envs/env_dirs/plmblast/lib/python3.10/site-packages/pandas/core/indexing.py", line 1103, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/resources/conda_envs/env_dirs/plmblast/lib/python3.10/site-packages/pandas/core/indexing.py", line 1343, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/home/resources/conda_envs/env_dirs/plmblast/lib/python3.10/site-packages/pandas/core/indexing.py", line 1293, in _get_label
    return self.obj.xs(label, axis=axis)
  File "/home/resources/conda_envs/env_dirs/plmblast/lib/python3.10/site-packages/pandas/core/generic.py", line 4095, in xs
    loc = index.get_loc(key)
  File "/home/resources/conda_envs/env_dirs/plmblast/lib/python3.10/site-packages/pandas/core/indexes/range.py", line 349, in get_loc
    raise KeyError(key)
KeyError: 'g001590.m1_alloascoidea_hylecoeti'
`

**Comment by staszekdh** [comment]
@DaRinker Thank you for providing the sample data. The issue should now be resolved.
